### ISSUE TITLE
faster `yarn serve` startup possible?

### ISSUE THREAD

**Issue by lastobelus** [DynamoMTL/shopify-pipeline#100]
Is there a way to leverage themekit's relatively new `theme.lock` mechanism to avoid having to wait so long for `yarn serve` to start up by only uploading assets that have actually changed? or even just to upload what's needed for HMR and open the site first, then upload assets?

**Comment by nddery** [comment]
We are using version 0.6.11 of https://github.com/Shopify/node-themekit, which does not seem to support the new `theme.lock` feature - and the latest 0.6.12 only seems to be changes in the README.

On `yarn serve`, only assets that can't be serve locally are uploaded (so all liquid files, settings, ...) while JS, CSS and images are served through the dev-server.

Themekit's `theme.lock` looks interesting, and when it becomes available in the node version it'll be interesting to update.
