### ISSUE TITLE
Using liquid tags in SASS files

### ISSUE THREAD

**Issue by porschuetz** [DynamoMTL/shopify-pipeline#107]
We have been trying to reference assets in our SASS files, like the Debut Theme from Shopify for example is using.

`background-image: url('{{ "svg/ico-select.svg" | asset_url }}');`

Your recommended method is to use the generated SVG sprites and integrate any SVG into the DOM markup.

Can you say for sure that liquid parsing the SASS  is not possible to recreate? 
Thanks, Tilman

**Comment by nddery** [comment]
Since we do not upload images, stylesheets and scripts to Shopify during development, no, liquid parsing won't work.

Have you tried to reference your image normally as you'd do in normal CSS ? ie.:

```css
.some-selector {
  background-image: url('../images/svg/ico-select.svg');
}
```

[css-loader](https://github.com/webpack-contrib/css-loader) will find these and resolves them.

**Comment by porschuetz** [comment]
@nddery hey nicolas, thanks that works excellent.
