### ISSUE TITLE
Import JS file

### ISSUE THREAD

**Issue by francisneedham** [DynamoMTL/shopify-pipeline#110]
Hi,
already wrote on this - still no luck !

In my index.js file i put
import CheckImg from '../images/check_icon.svg'
and then  i console log it
console.log(CheckImg)

in dev => 
https://localhost:8080/check_icon.8f418bdc803872eb7418758b962f0f7d.svg

in production =>
check_icon.8f418bdc803872eb7418758b962f0f7d.svg

it's missing the CDN path.

what i'm doing wrong ?

thanks

f

**Comment by nddery** [comment]
Sorry in the delay to responding to #109, I'll close this one in favor of the other one.
