### ISSUE TITLE
Checkout.scss

### ISSUE THREAD

**Issue by francisneedham** [DynamoMTL/shopify-pipeline#111]
Hi,
we have to include the checkout.scss file in our assets folder to enable checkout customization ( this is  the only way shopify can make this possible only for plus merchants )

of course if i copy the file in the src/asset folder it won't make it to the dist folder.

any suggestions ?

thanks !

**Comment by alexleclair** [comment]
You can simply add it within `src/assets/vendors/`

**Comment by francisneedham** [comment]
it will compile to root / asset folder ?

**Comment by alexleclair** [comment]
Yup, anything placed within `src/assets/vendors` gets copied over `dist/assets/` :)

**Comment by francisneedham** [comment]
FANTASTIC :) THANKS !
