### ISSUE TITLE
All of settings_data.json is overwritten (wiped) on deploy

### ISSUE THREAD

**Issue by oliverchank** [DynamoMTL/shopify-pipeline#88]
Since all the content from the Customize Theme is saved on the Shopify side of things (```config/settings_data.json```) and not in the local file, using ```deploy``` will overwrite all the online data with an empty ```settings_data.json```. 

I'm not sure if downloading a copy of settings_data.json would/could be a solution, or simply ommit settings_data.json from being overwritten by default (with maybe another command to fully clean a theme).

/summoning @simonwalsh for white glove support. ;)

**Comment by simonwalsh** [comment]
@oliverchank Good call, we will look into it and figure something out. I think what makes the most sense is to simply ignore that .json file, as a v1.

**Comment by nddery** [comment]
In your `config/shopify.yml` file, you can add the following lines to the desired environment to ignore `settings_data.json`.

```yaml
[environment]:
  ...
  ignore_files
    - settings_data.json
```

We'll update the config file created for new project.
