### ISSUE TITLE
Vendors pass-through not working for script tags?

### ISSUE THREAD

**Issue by lastobelus** [DynamoMTL/shopify-pipeline#98]
The `assets/vendors` + single-quote passthru mechanism, is not working for me with script tags:

If I use:

```
<script src='{{ 'match-media.min.js' | asset_url }}'></script>
```
I get:
```
Error: Cannot find module '/XXX/shopify-pipeline-test/src/layout/match-media.min.js'
```

And if I try to add in the relative path:
```
  <script src='{{ '../assets/vendor/match-media.min.js' | asset_url }}'></script>
```

Webpack tries to compile it and I get:
```
ReferenceError: window is not defined (or other error caused by trying to compile an oldskool js file with transpiler)
```

Have I misunderstood something about how to set this up?

Also, I think passthru should also work with `{{ 'some_path' | asset_url | script_tag}}`.

**Comment by nddery** [comment]
What happens if you use double quotes inside of the `src` attribute ? Like so:

```
<script src='{{ "match-media.min.js" | asset_url }}'></script>
```

The reason to use single quote around the `src` attribute is so that we can use double quotes inside the liquid expression.

**Comment by lastobelus** [comment]
Duh! yes, it works and I feel chagrined.
