### ISSUE TITLE
typo on webpack.base.conf.js

### ISSUE THREAD

**Issue by dturton** [DynamoMTL/shopify-pipeline#99]
Small typo on webpack.base.conf.js on |**jpf**| line 127

https://github.com/DynamoMTL/shopify-pipeline/blob/d57fc2a19ff090dfdb793d08d63ddb9a2efae5b2/config/webpack.base.conf.js#L127

**Comment by nddery** [comment]
Thanks for reporting this, we'll push this in a new version soon.
